[package]
name = "portalvis"
version = "0.1.0"
authors = ["Erika <rrika9@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lpsolve = "*"
lpsolve-sys = "*"
crossbeam = "*"
